name: "CI Install Script"

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test Install Script (Linux)
      run: |
        sh install.sh
        extism-js --version
      if: runner.os != 'Windows'

    - name: Test Install Script Part1 (Windows)
      run: |
        powershell -executionpolicy bypass -File .\install-windows.ps1
      if: runner.os == 'Windows'

    - name: Test Install Script Part2 (Windows)
      run: |
        extism-js --version
      if: runner.os == 'Windows'
